[ccc]

### Toggle application level debug (does not toggle framework debugging)
# debug = false

### Where external (third-party) plugins are loaded from
# plugin_dir = /var/lib/ccc/plugins/

### Where all plugin configurations are loaded from
# plugin_config_dir = /etc/ccc/plugins.d/

### Where external templates are loaded from
# template_dir = /var/lib/ccc/templates/

[log.colorlog]

### Where the log file lives (no log file by default)
file = /var/log/ccc/ccc.log

### The level for which to log.  One of: info, warn, error, fatal, debug
level = debug

### Whether or not to log to console
to_console = false

### Whether or not to rotate the log file when it reaches `max_bytes`
rotate = true

### Max size in bytes that a log file can grow until it is rotated.
max_bytes = 1000000

### The maximum number of log files to maintain when rotating
max_files = 7

### Colorize the log file
colorize_file_log = true

### Colorize the console log
colorize_console_log = true

[letsencrypt]

### Default key length for SSL certificates
keylength = "ec-384"

[php]

### Default PHP version
version = 8.3

[mysql]

### Default MySQL version
version = 8.0

### MySQL grant host
grant-host = localhost
